# Generated by Django 4.0.3 on 2022-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Success')], default=0),
        ),
    ]
